steps:
  # Build the container image with Firebase client config
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['./cloudbuild-docker.sh']
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    secretEnv: ['_FIREBASE_API_KEY', '_FIREBASE_AUTH_DOMAIN', '_FIREBASE_PROJECT_ID', '_FIREBASE_STORAGE_BUCKET', '_FIREBASE_MESSAGING_SENDER_ID', '_FIREBASE_APP_ID', '_DATABASE_URL']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/how-scary-wiki:latest']
  
  # Deploy container image to Cloud Run with secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'how-scary-wiki'
      - '--image'
      - 'gcr.io/$PROJECT_ID/how-scary-wiki:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '100'
      - '--add-cloudsql-instances'
      - 'how-scary-wiki:us-central1:how-scary-wiki'
      - '--set-env-vars'
      - 'NODE_ENV=production,GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=us-central1'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,NEXT_PUBLIC_FIREBASE_API_KEY=FIREBASE_API_KEY:latest,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=FIREBASE_AUTH_DOMAIN:latest,NEXT_PUBLIC_FIREBASE_PROJECT_ID=FIREBASE_PROJECT_ID:latest,NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=FIREBASE_STORAGE_BUCKET:latest,NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=FIREBASE_MESSAGING_SENDER_ID:latest,NEXT_PUBLIC_FIREBASE_APP_ID=FIREBASE_APP_ID:latest,GOOGLE_KNOWLEDGE_GRAPH_API_KEY=GOOGLE_KG_API_KEY:latest,FIREBASE_ADMIN_PROJECT_ID=FIREBASE_ADMIN_PROJECT_ID:latest,FIREBASE_ADMIN_CLIENT_EMAIL=FIREBASE_ADMIN_CLIENT_EMAIL:latest,FIREBASE_ADMIN_PRIVATE_KEY=FIREBASE_ADMIN_PRIVATE_KEY:latest'

images:
  - 'gcr.io/$PROJECT_ID/how-scary-wiki:latest'

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_API_KEY/versions/latest
      env: '_FIREBASE_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_AUTH_DOMAIN/versions/latest
      env: '_FIREBASE_AUTH_DOMAIN'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_PROJECT_ID/versions/latest
      env: '_FIREBASE_PROJECT_ID'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_STORAGE_BUCKET/versions/latest
      env: '_FIREBASE_STORAGE_BUCKET'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: '_FIREBASE_MESSAGING_SENDER_ID'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_APP_ID/versions/latest
      env: '_FIREBASE_APP_ID'
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: '_DATABASE_URL'