steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/how-scary-wiki:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/how-scary-wiki:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'how-scary-wiki'
      - '--image'
      - 'gcr.io/$PROJECT_ID/how-scary-wiki:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '100'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--update-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL},NEXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY},NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID},GOOGLE_KNOWLEDGE_GRAPH_API_KEY=${_GOOGLE_KG_API_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/how-scary-wiki:$COMMIT_SHA'